### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file during installation in alpine docker container

### ISSUE THREAD

**Issue by johnnyEmpires** [johnnyEmpires/basiclog#2]
Below error is reported when installing the `whl` file inside the container

```
~ # pip install basiclog-0.2.4-py3-none-any.whl
Processing ./basiclog-0.2.4-py3-none-any.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 103, in resolve
    r = self.factory.make_requirement_from_install_req(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 429, in make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
    super().__init__(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 61, in _get_prepared_distribution
    return abstract_dist.get_pkg_resources_distribution()
  File "/usr/lib/python3.9/site-packages/pip/_internal/distributions/wheel.py", line 27, in get_pkg_resources_distribution
    with ZipFile(self.req.local_file_path, allowZip64=True) as z:
  File "/usr/lib/python3.9/zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.9/zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Dockerfile
```
FROM alpine:3.14

WORKDIR /root

ADD .ashrc /root
ADD downloader.py /root
ADD snowflake-jdbc-3.13.3.jar /root
ADD spark-snowflake_2.12-2.9.0-spark_3.1.jar /root

# convert windows formatted file to unix-like
RUN dos2unix /root/.ashrc
RUN dos2unix /root/downloader.py

ENV ENV=/root/.ashrc

RUN apk add --no-cache python3 py3-pip

ADD requirements.txt /root

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add --update --no-cache py3-numpy py3-pandas@testing

RUN python3 -m pip install -r /root/requirements.txt && \
    cp /root/snowflake-jdbc-3.13.3.jar /usr/lib/python3.9/site-packages/pyspark/jars && \
    cp /root/spark-snowflake_2.12-2.9.0-spark_3.1.jar /usr/lib/python3.9/site-packages/pyspark/jars
```

**Comment by johnnyEmpires** [comment]
Can be installed while building the image. Added the following lines in `Dockerfile` to install during build time.
```
ADD basiclog-0.2.4-py3-none-any.whl /root
RUN python3 -m pip install /root/basiclog-0.2.4-py3-none-any.whl
```

Seems problem is due to incomplete download file.
